[package]
name = "testroute"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
inquire = "0.7.5"
serde = "1.0.208"
serde_json = "1.0.125"
strum = "0.26.3"
strum_macros = "0.26.4"
tokio = { version = "1.39.3", features = ["full"]}
